baseURL: http://example.org/
defaultContentLanguage: fr
languageCode: fr-fr
title: Sourcyou
theme: bootpro
copyright: Tsvetomira TSVETKOVA EIRL

languages:
  fr:
    languageName: Français
    weight: 1

params:
  useStoryset: 1
  email: mira@sourcyou.fr
  phone: 07.66.08.12.02

  nav:
  - title: Mes offres
    link: /mes-offres
  - title: Un nouveau poste
    link: /mes-offres/agent-de-carriere
  - title: Comment je travaille
    link: /comment-je-travaille
  - title: Mes tarifs
    link: /tarifs

  socials:
    linkedin: https://www.linkedin.com/in/mira-tsvetkova/

markup:
  goldmark:
    renderer:
      unsafe: true